---
title: "kNN_Cancer"
author: "mzakaria"
date: "April 19, 2018"
#output: html_document
always_allow_html: yes # this is for wordcloud2 output
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Required packages
```{r}
#install.packages("class") # for kNN classification
library(class)
#install.packages("gmodels") # for CrossTable function at the evaluation
library(gmodels)
library(visdat) # better data exploration with vis_dat
library(assertr) # mkae assert statements for better data quality
library(dplyr)
```


```{r}
#plot(cars)
wbcd <- read.csv(file = "C:/Users/mkzak/Documents/GitHub/FunWithR/FunWithR/1_kNN/wisc_bc_data.csv", stringsAsFactors = FALSE)

str(wbcd)
summary(wbcd)

# remove id

wbcd <- wbcd[-1]

```

Lets try a better visualization with visdat

```{r}
vis_dat(wbcd)
```

```{r}
vis_miss(wbcd)
```


I'd like to make one asser statement regarding the radius of the tumers

```{r}
invisible(
  wbcd %>% 
    verify(c( "B", "M") %in% .$diagnosis) %>% 
          assert(within_bounds(0,Inf), radius_mean) 
)
```

